# -*- coding: utf-8 -*-
"""sentence similarity project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vz7ggFd2CUvV2In18n4JUCfFUJmHguG4
"""

! pip install sentence_transformers

#util-utilizer-help to understsnd the language we given
#alminilml6v2 search in google
from sentence_transformers import SentenceTransformer,util
# load the model
model=SentenceTransformer('all-MiniLM-L6-v2')
text1=input("Enter Text 1: ")
text2=input("Enter Text 2: ")
embedding1=model.encode(text1)
embedding2=model.encode(text2)
#calculate similarity
similarity=util.cos_sim(embedding1,embedding2)
#show result
print("\nSimiralrity score:",round(float(similarity),2))
if similarity>0.75:
  print("similarity level:High")
elif similarity>0.4:
  print("similarity level:Medium")
else:
  print("similarity level:Low")